# Generated by Django 3.2.6 on 2021-10-14 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdnet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sample',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='tekijikaiji',
            table='tekijikaiji',
        ),
    ]
