# Generated by Django 3.2.6 on 2021-10-14 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdnet', '0002_auto_20211014_0145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_address', models.TextField(primary_key=True, serialize=False)),
                ('customer', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Sample',
        ),
    ]
