# Generated by Django 3.2.6 on 2021-10-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdnet', '0003_auto_20211014_0210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.TextField(blank=True, null=True)),
                ('code', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'code',
                'managed': False,
            },
        ),
    ]
